/* Mark Your Presence — Press & Media Coverage */
window.MYP_PRESS = [
  { title: "Vote, an honour for this young man", outlet: "Mid-Day", category: "awards", year: "2019", url: "https://www.mid-day.com/mumbai/mumbai-news/article/vote-an-honour-for-this-young-man-23180949", featured: true },
  { title: "Mumbai Diary: Monday Dossier", outlet: "Mid-Day", category: "news", year: "2019", url: "https://www.mid-day.com/amp/mumbai/mumbai-news/article/mumbai-diary-monday-dossier-23351295" },
  { title: "Mumbai Diary: Saturday Dossier", outlet: "Mid-Day", category: "news", year: "2019", url: "https://www.mid-day.com/amp/mumbai/mumbai-news/article/mumbai-diary-saturday-dossier-23346230" },
  { title: "I want mala pahije — mujhe chahiye, mare je i e che", outlet: "Sunday Mid-Day", category: "news", year: "2019", url: "https://www.mid-day.com/sunday-mid-day/article/i-want-mala-pahije-mujhe-chahiye-mare-je-i-e-che-23352229" },
  { title: "Meet Chaitanya Prabhu, awarded the Diana Award", outlet: "ABP News", category: "video", year: "2019", url: "https://www.abplive.com/videos/news/india-meet-chaitanya-prabhu-who-was-awarded-the-diana-award-1935373", featured: true },
  { title: "Law student helps register 10,000 first-time voters", outlet: "Mumbai Mirror", category: "news", year: "2019", url: "https://mumbaimirror.indiatimes.com/maharashtra-assembly-elections/news/law-student-helps-register-10000-first-time-voters/articleshow/71432384.cms", featured: true },
  { title: "Democracy Day 2020: Connecting dance with democracy", outlet: "Mumbai Mirror", category: "news", year: "2020", url: "https://mumbaimirror.indiatimes.com/mumbai/other/democracy-day-2020-connecting-dance-with-democracy/articleshow/78111541.cms" },
  { title: "Delhi elections & the voters Chaitanya Prabhu reached", outlet: "YourStory", category: "news", year: "2019", url: "https://yourstory.com/socialstory/2019/12/delhi-elections-voters-chaitanya-prabhu-mark-your-presence" },
  { title: "This law student wants to make voting fun and cool", outlet: "The Wire", category: "news", year: "2019", url: "https://livewire.thewire.in/politics/this-law-student-wants-to-make-voting-fun-and-cool/" },
  { title: "Nurturing young voters", outlet: "Asian Age", category: "news", year: "2019", url: "https://asianage.com/life/more-features/181019/nurturing-young-voters.html" },
  { title: "Students use rap songs and rallies to educate voters", outlet: "Hindustan Times", category: "news", year: "2019", url: "https://www.hindustantimes.com/mumbai-news/maha-polls-students-use-rap-songs-and-hold-rallies-to-educate-voters/story-5fsBEZwL9pZ3Tj1uBmawKP.html", featured: true },
  { title: "Democracy Day episode — Morning No. 1 with Malishka", outlet: "Spotify / Red FM", category: "audio", year: "2020", url: "https://open.spotify.com/episode/56fbj5mIonBoBnzfaLCFfT?si=hKIWZIfISBmopUNE-1YTnQ" },
  { title: "Working for change, one voter at a time", outlet: "The Hindu", category: "news", year: "2019", url: "https://www.thehindu.com/elections/lok-sabha-2019/working-for-change-one-voter-at-a-time/article27006027.ece", featured: true },
  { title: "Founder's interview by Malishka, Red FM", outlet: "YouTube", category: "video", year: "2019", url: "https://youtu.be/mJDNWnQ85qM" },
  { title: "20-year-old educating Mumbaikars about voting & voter ID", outlet: "Audioboom / Red FM", category: "audio", year: "2019", url: "https://audioboom.com/posts/7215239-20-year-young-chaitanya-prabhu-educating-mumbaikars-about-voting-and-registration-for-a-voters-id" },
  { title: "Mark Your Presence initiative to raise political awareness", outlet: "Free Press Journal", category: "news", year: "2019", url: "https://www.freepressjournal.in/mumbai/mumbai-lads-mark-your-presence-initiative-to-raise-political-awareness" },
  { title: "NSS Mumbai University voter town hall on BMC elections", outlet: "Free Press Journal", category: "news", year: "2022", url: "https://www.freepressjournal.in/mumbai/mark-your-presence-nss-mumbai-university-engage-650-students-in-voter-town-hall-on-bmc-elections" },
  { title: "Group composes rap to spread voting awareness", outlet: "Republic World", category: "news", year: "2019", url: "https://www.republicworld.com/amp/india-news/elections/maharashtra-elections-a-group-composes-rap-to-spread-voting-awareness.html" },
  { title: "Pehla Vote Pehla Pyaar — voting awareness through rap", outlet: "Lokmat", category: "video", year: "2019", url: "https://youtu.be/W8AYRpB99og" },
  { title: "Pehla Vote Pehla Pyaar — youngsters' rap for voting", outlet: "Times Now Hindi", category: "news", year: "2019", url: "https://www.timesnowhindi.com/trending-viral/article/pahla-vote-pahla-pyar-awareness-for-voting-by-making-rap-listen-beat-of-youngsters-out-of-mouth/264821" },
  { title: "Youngsters compose rap song to urge people to vote", outlet: "ANI", category: "news", year: "2019", url: "https://www.aninews.in/news/national/general-news/youngsters-compose-rap-song-to-urge-people-to-vote-in-maharashtra-polls20191020150944/?amp=1" },
  { title: "Pehla Vote Pehla Pyaar — rappers urge people to cast vote", outlet: "Indian Express", category: "news", year: "2019", url: "https://indianexpress.com/elections/pehla-vote-pehla-pyaar-rappers-urge-people-to-cast-vote-in-a-musical-style-6076919/", featured: true },
  { title: "Mumbai rappers raise awareness about voting", outlet: "Latestly", category: "news", year: "2019", url: "https://www.latestly.com/social-viral/mumbai-rappers-raise-awareness-about-voting-ahead-of-maharashtra-assembly-elections-2019-watch-rap-song-video-1281461.html" },
  { title: "Mark Your Presence on Under 25", outlet: "Instagram", category: "social", year: "2019", url: "https://www.instagram.com/p/B3_8TgYDhgu/?igshid=bhn0p0a68ggt" },
  { title: "Pehla Vote Pehla Pyaar — musical voting appeal", outlet: "Top India News", category: "news", year: "2019", url: "https://topindinews.com/india/pehla-vote-pehla-pyaar-rappers-urge-people-to-cast-vote-in-a-musical-style/" },
  { title: "22-year-old law student on a mission for educated voters", outlet: "Sound & Light", category: "news", year: "2020", url: "https://www.soundnlight.in/meet-the-22-year-old-law-student-and-national-athlete-who-is-on-a-mission-to-turn-youth-into-educated-voters/" },
  { title: "Tinder's Every Single Vote Counts awareness campaign", outlet: "Deccan Chronicle", category: "partnerships", year: "2024", url: "https://www.deccanchronicle.com/lifestyle/relationship/tinders-every-single-vote-counts-awareness-campaign-for-daters-890037" },
  { title: "Tinder's unique pre-poll voting campaign", outlet: "ET Now", category: "partnerships", year: "2024", url: "https://www.etnownews.com/technology/voting-partner-needed-dating-app-tinders-unique-pre-poll-campaign-details-article-109408096" },
  { title: "Tinder launches Every Single Vote Counts for first-time voters", outlet: "Hindustan Times", category: "partnerships", year: "2024", url: "https://tech.hindustantimes.com/amp/tech/news/tinder-launches-every-single-vote-counts-campaign-to-empower-first-time-voters-in-india-71713443475659.html" },
  { title: "Tinder has an election day appeal for users", outlet: "Times of India", category: "partnerships", year: "2024", url: "https://timesofindia.indiatimes.com/technology/social/tinder-has-an-election-day-appeal-for-users/amp_articleshow/109409329.cms" },
  { title: "Tinder encouraging first-time daters to become first-time voters", outlet: "Zee News", category: "partnerships", year: "2024", url: "https://zeenews.india.com/hindi/technology/lok-sabha-elections-2024-tinder-encouraging-first-time-daters-to-become-first-time-voters/2210808" },
  { title: "India Elections 2024 — Tinder Pressroom", outlet: "Tinder Pressroom", category: "partnerships", year: "2024", url: "https://in.tinderpressroom.com/2024-04-17-India-Elections" },
  { title: "Make policies youth-centric — why the youth vote matters", outlet: "ADR India", category: "policy", year: "2024", url: "https://adrindia.org/content/make-policies-are-youth-centric-experts-why-youth-vote-matters" },
  { title: "A bridge between the shore and sun", outlet: "Mumbai Mirror — Opinion", category: "opinion", year: "2025", url: "https://mumbaimirror.indiatimes.com/opinion/a-bridge-between-the-shore-and-sun/articleshow/131207022.html", featured: true },
  { title: "Climate week or corporate week?", outlet: "Mumbai Mirror — Opinion", category: "opinion", year: "2025", url: "https://mumbaimirror.indiatimes.com/opinion/climate-week-or-corporate-week/articleshow/128511151.html" },
  { title: "Mumbai deserves a hoarding-free future", outlet: "Mumbai Mirror — Opinion", category: "opinion", year: "2025", url: "https://mumbaimirror.indiatimes.com/opinion/mumbai-deserves-a-hoarding-free-future/articleshow/130397249.html" },
];

window.MYP_PRESS_CATEGORIES = {
  all: "All Coverage",
  awards: "Awards & Recognition",
  news: "National & Regional News",
  video: "TV & Video",
  audio: "Radio & Podcast",
  opinion: "Opinion & Columns",
  partnerships: "Partnerships",
  policy: "Policy & Civic",
  social: "Social Media",
};
